Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
to print the data types of both the variables.

Ans:

Yes, there is a difference in the data type of variables list_ and array_list. list_ is a list of strings, while array_list is a numpy array of strings.

In [2]:
import numpy as np
list = ['1', '2', '3', '4', '5']
arraylist = np.array(list_)
print("Type of list_:", type(list))
print("Type of array_list:", type(arraylist))


Type of list_: <class 'list'>
Type of array_list: <class 'numpy.ndarray'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [3]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
# Printing data type of each element in list_
for element in list_:
    print(type(element))
    
# Printing data type of each element in array_list
for element in np.nditer(array_list):
    print(type(element))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and 
arra_list? If so then print the data types of each and every element present in both the variables, list_ 
and arra_list.

Ans:

Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list. The elements in list_ are strings, whereas the elements in array_list will be integers due to the dtype=int argument.

In [4]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)
# print data types of elements in list_
for elem in list_:
    print(type(elem))
    
# print data types of elements in array_list
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i)	 shape
(ii) size

In [5]:
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only,using a numpy array creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
import numpy as np
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
import numpy as np
identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
